=== JangCool/code-generator/generator/dtd/generator.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	* : 요소가 가지고 있지 않거나 1개 이상 가질 수 있음.
	+ : 자식요소가 최소 하나 이상 가질 수 있음
	? : 단 하나의 요소만 가질 수 있음.
	
	#REQUIRED : 필수속성(생량X) 절대 생략 되지 않는다.
    #IMPLIED : 선택속성(생략O) 써도인정 안써도 인정
    #FIXED "값" : 속성 고정값 #FIXED "축구부" : 반드시 축구부만 사용할수 있다.
	"값" : 속성 기본값 gen CDATA "m" : FIXED 와 비슷하게 사용 가능하다.
-->

<!-- configuration(root) 엘리먼트 정의-->		
<!ELEMENT configuration (properties?,jdbc?,global?,controllers*,services*,views*,javascripts*,tables*) >

<!-- properties 엘리먼트 정의-->		
<!ELEMENT properties (property*)>
	<!ELEMENT property EMPTY>
		<!ATTLIST property
			key CDATA #REQUIRED
			value CDATA #REQUIRED
		>

<!-- jdbc 엘리먼트 정의-->		
<!ELEMENT jdbc EMPTY>
	<!ATTLIST jdbc
		url CDATA #REQUIRED
		driver-class CDATA #REQUIRED
		username CDATA #REQUIRED
		password CDATA #REQUIRED
	>
	

<!-- global 엘리먼트 정의-->		
<!ELEMENT global (sql-session?,base-backage?,base-path?,exclude-column?)>
	<!ELEMENT sql-session EMPTY>
		<!ATTLIST sql-session
			name CDATA #REQUIRED
		>
	<!ELEMENT base-backage EMPTY>
		<!ATTLIST base-backage
			controller CDATA #REQUIRED
			service CDATA #REQUIRED
			repository CDATA #REQUIRED
			model CDATA #REQUIRED
			client CDATA #REQUIRED
		>
	<!ELEMENT base-path EMPTY>
		<!ATTLIST base-path
			template CDATA #REQUIRED
			source CDATA #REQUIRED
			resources CDATA #REQUIRED
			views CDATA #REQUIRED
			javascripts CDATA #REQUIRED
	<!ELEMENT exclude-column EMPTY>
		<!ATTLIST exclude-column
			insert CDATA #REQUIRED
			update CDATA #REQUIRED

<!-- controllers 엘리먼트 정의-->		
<!ELEMENT controllers (controller*)>
	<!ATTLIST controllers
		business CDATA #IMPLIED
		package CDATA #IMPLIED
		suffix-package CDATA #IMPLIED
		type (rest | normal) #IMPLIED
	>
	<!ELEMENT controller EMPTY>
	<!ATTLIST controller
		name CDATA #REQUIRED
		request-mapping CDATA #IMPLIED
		type (rest | normal) #IMPLIED
		all-in-one (false | true) #IMPLIED
		
	>
	
<!-- services 엘리먼트 정의-->		
<!ELEMENT services (service*)>
	<!ATTLIST services
		business CDATA #IMPLIED
		package CDATA #IMPLIED
		suffix-package CDATA #IMPLIED
		proxy-target-class (false | true) #IMPLIED
	>
	<!ELEMENT service EMPTY>
	<!ATTLIST service
		name CDATA #REQUIRED
	>
	
<!-- jsp 엘리먼트 정의-->		
<!ELEMENT views (jsp*)>
	<!ATTLIST views
		business CDATA #IMPLIED
		target CDATA #IMPLIED
		suffix-target CDATA #IMPLIED
	>
	<!ELEMENT jsp EMPTY>
	<!ATTLIST jsp
		name CDATA #REQUIRED
	>
	
<!-- js 엘리먼트 정의-->		
<!ELEMENT javascripts (js*)>
	<!ATTLIST javascripts
		business CDATA #IMPLIED
		target CDATA #IMPLIED
		suffix-target CDATA #IMPLIED
	>
	<!ELEMENT javascript EMPTY>
	<!ATTLIST javascript
		name CDATA #REQUIRED
	>
	
<!-- table 엘리먼트 정의-->		
<!ELEMENT tables (table*)>
	<!ATTLIST tables
		business CDATA #IMPLIED
		package CDATA #IMPLIED
		suffix-package CDATA #IMPLIED
		sqlsession CDATA #IMPLIED
		base-repository (true | false) #IMPLIED
		base-model (true | false) #IMPLIED
		base-mappers (true | false) #IMPLIED
		only (model | dao | mappers) #IMPLIED
	>
	<!ELEMENT table (column*)>
	<!ATTLIST table
		name CDATA #REQUIRED
		sqlsession CDATA #IMPLIED
		rename CDATA #IMPLIED
		desc CDATA #IMPLIED
		alias CDATA #IMPLIED
		suffix CDATA #IMPLIED
		prefix CDATA #IMPLIED
		lock (select) #IMPLIED
	>
	<!ELEMENT column EMPTY>
	<!ATTLIST column
		name CDATA #REQUIRED
		alias CDATA #IMPLIED
		jdbcType CDATA #IMPLIED
		typeHandler CDATA #IMPLIED
		type (auto | date) #IMPLIED
		type-value CDATA #IMPLIED
		
	>

=== JangCool/code-generator/generator/generator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "dtd/generator.dtd">
<configuration>

	<properties>
		<property key="package.base" value="com.zen9.capelion.base"></property>
	</properties>

	<!-- db 접속 정보 설정 -->
	<jdbc
		url="jdbc:mysql://db.zen9.com:53306/missha?characterEncoding=utf8&amp;serverTimezone=Asia/Seoul"
		driver-class="com.mysql.jdbc.Driver"
		username="missha"
		password="missha2019!@"
	/>

	<global>
		<base-package 
			controller = "${package.base}"
			service = "${package.base}"
			target = "${package.base}"
		/>
	</global>

	<!-- start member -->
   <controllers business="member" suffix-package="controller">
      <controller name="Member" />
   </controllers>
   
   <controllers business="SS" suffix-package="controller">
      <controller name="SS" />
   </controllers>
   

   <services business="order" suffix-package="service" proxy-target-class="true">   
      <service name="BaseOrder"></service>
   </services>

<!--     <tables business="common" suffix-package="repository"> -->
<!--        <table name="CM_SITE" desc="사이트 관리" /> -->
<!--     </tables> -->
    
   <!-- end member -->
   
	<!--  Start of Marketing -->
	<!--
	<services business="marketing" suffix-package="service" proxy-target-class="true">   
	    <service name="BaseMarketing"/>
	    <service name="BasePromotion"/>
	    <service name="BaseEvent"/>
	</services>
	<tables business="marketing" suffix-package="repository">
	    <table name="MK_PRMO" desc="프로모션" />
	    <table name="MK_PRMO_BENF_TGT" desc="프로모션 혜택 대상" />
	    <table name="MK_PRMO_PAY_STEP" desc="프로모션 지급 단계" />
	    <table name="MK_PRMO_PAY_TGT" desc="프로모션 지급 대상" />
	    <table name="MK_CPN_AUTHN" desc="쿠폰 인증" />
	</tables>
	<services business="member" suffix-package="service" proxy-target-class="true">   
	    <service name="BaseMemberCoupon"/>
	</services>
	<tables business="member" suffix-package="repository">
	    <table name="MB_MBR_CPN" desc="회원 쿠폰" />
	</tables>
	-->
	<!--  End of Marketing -->
	
	<tables business="order" suffix-package="repository">
		<table name="OD_ORD_GOODS"  desc="OD_주문상품" />
	</tables>
	
	


</configuration>
